project:
  type: website
  output-dir: docs

website:
  title: "New TA and Grad Student Orientation Week"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Sessions
        menu:
          - text: Intro
            href: 01-introduction.qmd
          - text: Course Planning
            href: 02-course-planning.qmd
          - text: Assessment
            href: 03-assessment.qmd
          - text: Syllabus
            href: 04-syllabus.qmd
          - text: Activities
            href: 06-activities.qmd
          - text: Policies
            href: 05-policies.qmd
          - text: Microteaching
            href: 07-microteaching.qmd
      - text: GSA Grad Guidebook
        href: https://unl-statistics.github.io/IncomingStudentHandbook/


format:
  html:
    theme: simplex
    css: [styles.css, unl.scss]
    toc: true



