---
title: "New TA and Grad Student Orientation Week"
---

# Schedule

```{r, child = 'schedule2.qmd'}
```


# Other Information

::: {.callout-note .column-page}
## Teaching and Orientation (UNL-wide)

- [UNL Grad Studies Orientation](https://www.unl.edu/gradstudies/welcome) (Canvas)
- [UNL Grad Studies Institute for International Teaching Assistants](https://www.unl.edu/gradstudies/professional-development/teaching-development/ita)    
This program takes place 2 weeks before orientation week and is extremely valuable for both domestic and international students. It is required for international students (unless you have a Masters degree from an English-language university). 
:::

::: {.callout-note .column-page}
## Information for Incoming Students

Our department's Graduate Student Association (GSA) maintains an informal [handbook](https://unl-statistics.github.io/IncomingStudentHandbook/) for new graduate students that includes information such as 

- how to register for classes
- how to get UNL ID card and bus pas
- how to connect to campus WiFi
- housing resources
- places to go in Lincoln

and much, much more. [Check it out!](https://unl-statistics.github.io/IncomingStudentHandbook/)

:::
