::: {.callout-tip .column-page}
### Monday

+----------------------------------------------+-----------+-----------------------------------+--------------------------------------+
| Event                                        | Time      | Location                          | Who?                                 |
+==============================================+===========+===================================+======================================+
| New Graduate Student Orientation             | 9-11 am   | Hardin 49                         | All new statistics graduate students |
+----------------------------------------------+-----------+-----------------------------------+--------------------------------------+
| [Stat 218 Introduction](01-introduction.qmd) | 12-2 pm   | Hardin Hall Large Conference Room | New TAs                              |
+----------------------------------------------+-----------+-----------------------------------+--------------------------------------+
| Department Meeting                           | 3-4:30 pm | Hardin Hall Auditorium            | Everyone                             |
+----------------------------------------------+-----------+-----------------------------------+--------------------------------------+
:::

::: {.callout-tip .column-page}
### Tuesday

+-----------------------------------------------------------------------------+--------+------------------------------+---------+
| Event                                                                       | Time   | Location                     | Who?    |
+=============================================================================+========+==============================+=========+
| [UNL TA Orientation](https://events.unl.edu/gradstudies/2022/08/16/165120/) | 8-1 pm | Nebraska Union (City Campus) | New TAs |
+-----------------------------------------------------------------------------+--------+------------------------------+---------+
:::

::: {.callout-tip .column-page}
### Wednesday

+----------------------------------------------------+-----------------+-----------+-------------------------------+
| Event                                              | Time            | Location  | Who?                          |
+====================================================+=================+===========+===============================+
| [Stat 218 Course Planning](02-course-planning.qmd) | 9-11 am         | Hardin 49 | New TAs + Stat 218 TAs        |
+----------------------------------------------------+-----------------+-----------+-------------------------------+
| Wiley Plus Training                                | 11:30 am - 2 pm | Hardin 49 | New TAs + Stat 218 TAs        |
+----------------------------------------------------+-----------------+-----------+-------------------------------+
| [Stat 218 Assessment](03-assessment.qmd)           | 2-3:30 pm       | Hardin 49 | New TAs + Stat 218 TAs        |
+----------------------------------------------------+-----------------+-----------+-------------------------------+
:::

::: {.callout-tip .column-page}
### Thursday

+----------------------------------------+--------------+-----------+------------------------+
| Event                                  | Time         | Location  | Who?                   |
+========================================+==============+===========+========================+
| [Stat 218 Syllabus](04-syllabus.qmd)   | 9-11 am      | Hardin 49 | New TAs + Stat 218 TAs |
+----------------------------------------+--------------+-----------+------------------------+
| Lunch (on your own)                    | 11-12:30 am  |           |                        |
+----------------------------------------+--------------+-----------+------------------------+
| [University Policies](05-policies.qmd) | 12:30 - 3 pm | Hardin 49 | ALL TAs                |
+----------------------------------------+--------------+-----------+------------------------+
:::

::: {.callout-tip .column-page}
### Friday

+---------------------------------------------------------------------------------------------------------------------------+------------------+-----------------------------------------+-------------------------------+
| Event                                                                                                                     | Time             | Location                                | Who?                          |
+===========================================================================================================================+==================+=========================================+===============================+
| [Stat 218 Activities](06-activities.qmd)                                                                                  | 10 am - 12:30 pm | Hardin 49                               | New TAs + Stat 218 TAs        |
+---------------------------------------------------------------------------------------------------------------------------+------------------+-----------------------------------------+-------------------------------+
| Lunch (on your own)                                                                                                       | 12:30 - 2 pm     |                                         |                               |
+---------------------------------------------------------------------------------------------------------------------------+------------------+-----------------------------------------+-------------------------------+
| [Stat 218 Microteaching](07-microteaching.qmd)                                                                            | 2 - 3:30 pm      | Hardin 49                               | New TAs                       |
+---------------------------------------------------------------------------------------------------------------------------+------------------+-----------------------------------------+-------------------------------+
| Student Welcome Dinner\                                                                                                   | 6pm              | Lazlo's Restaurant - Haymarket location | Everyone                      |
| ([RSVP](https://docs.google.com/forms/d/e/1FAIpQLSeq9MelnThsovox3cRawsbP_DbxtKqoZFme0hOMNtt7VYq0cw/viewform) by August 1) |                  |                                         |                               |
+---------------------------------------------------------------------------------------------------------------------------+------------------+-----------------------------------------+-------------------------------+
:::
